# -*- coding: utf-8 -*-
import json

def Q(enonce, reponse):
    return {"enonce": enonce, "reponse": reponse}

# ============================================================
# R485 - Gerbeurs à conducteur accompagnant
# ============================================================
r485_cg = [
    Q("Le CACES R485 est valable 5 ans avant réactualisation obligatoire.", True),
    Q("Le CACES atteste de l'aptitude du conducteur, il ne remplace pas l'autorisation de conduite délivrée par l'employeur.", True),
    Q("Un salarié titulaire du CACES peut conduire un gerbeur sans autorisation de conduite de son employeur.", False),
    Q("Le CACES R485 catégorie 2 dispense de la catégorie 1.", True),
    Q("Le CACES R485 catégorie 1 dispense de la catégorie 2.", False),
    Q("La catégorie 1 concerne les gerbeurs dont la hauteur de levée est comprise entre 1,20 m et 2,50 m.", True),
    Q("La catégorie 2 concerne les gerbeurs dont la hauteur de levée est supérieure à 2,50 m.", True),
    Q("Un transpalette à hauteur de levée auxiliaire inférieure à 1,20 m relève du CACES R485.", False),
    Q("Un chariot à conducteur porté avec plateforme rabattable relève du CACES R485.", False),
    Q("Un gerbeur tout-terrain relève du CACES R485.", False),
    Q("En cas d'échec à une seule des deux épreuves, le candidat conserve le bénéfice de la partie réussie pendant 12 mois.", True),
    Q("La date d'obtention du CACES est la date de réussite à la première des deux épreuves passées.", False),
    Q("Le test théorique R485 est identique pour les catégories 1 et 2.", True),
    Q("Il faut réussir à la fois l'épreuve théorique et l'épreuve pratique pour obtenir le CACES R485.", True),
    Q("Le CACES R485 permet à lui seul la délivrance d'une AIPR.", False),
]

r485_techno = [
    Q("La stabilité d'un gerbeur en charge dépend de la position du centre de gravité de l'ensemble chariot-charge.", True),
    Q("Plus la charge est levée haut, plus la stabilité du gerbeur augmente.", False),
    Q("Le tablier porte-fourche doit toujours être incliné vers l'avant pendant le déplacement en charge.", False),
    Q("Un gerbeur accompagnant se conduit en marchant à côté de l'appareil, jamais en étant porte.", True),
    Q("Le mât d'un gerbeur permet de guider la charge verticalement lors du levage.", True),
    Q("Les bras porteurs d'un gerbeur élargissent sa base de sustentation.", True),
    Q("Un gerbeur électrique fonctionne généralement sur batterie rechargeable.", True),
    Q("La vitesse de déplacement d'un gerbeur charge doit être réduite par rapport à un déplacement à vide.", True),
    Q("Le frein de service d'un gerbeur permet de l'immobiliser en cas d'urgence.", True),
    Q("Un gerbeur peut se renverser latéralement si un virage est pris trop rapidement en charge.", True),
    Q("La charge doit être positionnée le plus près possible du mât pour limiter le porte-à-faux.", True),
    Q("Le report de charge sur les bras porteurs augmente lorsque la charge est éloignée du mât.", True),
    Q("Un gerbeur de catégorie 2 est en général équipé d'un mât plus haut qu'un gerbeur catégorie 1.", True),
    Q("La capacité de charge d'un gerbeur reste identique quelle que soit la hauteur de levée.", False),
    Q("Le dispositif de fin de course en hauteur empêche le mât de dépasser sa hauteur maximale de levée.", True),
    Q("Un gerbeur peut être équipé d'un limiteur de charge qui bloque le levage en cas de surcharge.", True),
    Q("L'inclinaison latérale du sol réduit la stabilité du gerbeur en charge.", True),
    Q("En cas de surcharge, le gerbeur risque de basculer vers l'avant.", True),
    Q("La commande de translation d'un gerbeur accompagnant se trouve généralement sur le timon.", True),
    Q("Un dispositif de sécurité homme mort arrête les mouvements du gerbeur si le conducteur relâche la commande.", True),
    Q("Le gerbeur peut fonctionner sans problème sur un sol fortement dégradé ou en pente prononcée.", False),
    Q("Les roues d'un gerbeur doivent être adaptées au type de sol rencontré.", True),
    Q("Un gerbeur thermique est couramment utilisé en entrepôt fermé sans ventilation.", False),
    Q("La largeur de la base de sustentation influence directement la stabilité transversale du gerbeur.", True),
    Q("Un défaut d'entretien du système de freinage peut compromettre la stabilité du gerbeur à l'arrêt en pente.", True),
]

r485_tableau = [
    Q("La capacité de charge indiquée sur la plaque du constructeur diminue en général avec la hauteur de levée.", True),
    Q("L'abaque de charges permet de connaître la charge maximale admissible en fonction de la hauteur de levée.", True),
    Q("Il est possible de dépasser la charge maximale indiquée sur l'abaque si la charge est bien répartie.", False),
    Q("La plaque de charge doit être lisible et apposée sur le gerbeur de façon visible pour le conducteur.", True),
    Q("Le centre de gravité de la charge influence la capacité maximale admissible indiquée sur l'abaque.", True),
    Q("Une charge dont le centre de gravité est décalé nécessite de consulter l'abaque pour vérifier la capacité réelle admissible.", True),
    Q("L'abaque de charges est identique pour tous les modèles de gerbeurs, quelle que soit leur catégorie.", False),
    Q("En l'absence de plaque de charge lisible, le conducteur peut estimer la capacité à l'œil.", False),
    Q("La capacité nominale maximale d'un gerbeur catégorie 2 est généralement plus élevée que celle d'un catégorie 1.", True),
    Q("Il est interdit d'utiliser un gerbeur dont la plaque de charge est illisible ou absente.", True),
]

r485_exploitation = [
    Q("Avant toute utilisation, le conducteur doit vérifier l'état des fourches, des roues et du dispositif de freinage.", True),
    Q("Il est autorisé de transporter une personne sur les fourches du gerbeur pour accéder à un rayonnage.", False),
    Q("En cas d'anomalie constatée sur l'appareil, le conducteur doit le signaler et ne pas l'utiliser.", True),
    Q("Le gerbeur peut être utilisé pour tracter une remorque non prévue à cet effet.", False),
    Q("La visibilité doit être dégagée dans le sens du déplacement, y compris en marche arrière si besoin avec l'aide d'un tiers.", True),
    Q("Il est possible de circuler avec une charge élevée pour améliorer la visibilité.", False),
    Q("Le port de chaussures de sécurité est recommandé pour la conduite d'un gerbeur.", True),
    Q("Le conducteur peut s'écarter du gerbeur pour répondre au téléphone tout en laissant une charge en hauteur.", False),
    Q("En fin de poste, le gerbeur doit être stationné avec les fourches basses et le moteur coupé.", True),
    Q("Le transport de matières dangereuses avec un gerbeur nécessite des précautions particulières.", True),
    Q("Un gerbeur peut être utilisé pour soulever une personne sur une plateforme improvisée.", False),
    Q("Il est interdit de stationner ou circuler avec le gerbeur sur une zone de circulation de piétons sans signalisation.", True),
    Q("Le conducteur doit s'assurer que l'allée de circulation est suffisamment large avant de manœuvrer.", True),
    Q("Il est permis de gerber une charge sur un palettier sans vérifier la compatibilité de la charge admissible du niveau.", False),
    Q("Le conducteur doit ralentir à l'approche des intersections et angles morts.", True),
    Q("Un gerbeur peut être utilisé par un salarié non formé en cas d'absence du titulaire habituel.", False),
    Q("Le conducteur doit vérifier la stabilité de la palette avant de la gerber en hauteur.", True),
    Q("Il est autorisé de rouler avec le gerbeur en tenant un objet dans une main et le timon dans l'autre.", False),
    Q("Le déchargement d'un véhicule au moyen d'un gerbeur doit se faire avec le véhicule immobilisé et calé.", True),
    Q("Un gerbeur peut circuler sur une rampe d'accès à un quai sans vérifier sa pente maximale admissible.", False),
    Q("Le conducteur doit maintenir une distance de sécurité avec les autres gerbeurs ou chariots en mouvement.", True),
    Q("Il est possible de gerber une charge en la faisant basculer légèrement pour la caler dans le rayonnage.", False),
    Q("Le conducteur doit s'assurer que la zone de dépose est dégagée avant de poser la charge.", True),
    Q("Un gerbeur peut être utilisé pour pousser une autre charge au sol si besoin.", False),
    Q("Le port d'équipements de protection individuelle adaptés est requis pour la conduite du gerbeur.", True),
    Q("Il est interdit de gerber une charge instable ou mal palettisée.", True),
    Q("Le conducteur peut lever la charge en roulant simultanément à vitesse normale.", False),
    Q("La zone de travail doit être dégagée de tout obstacle avant le début de l'opération.", True),
    Q("Un gerbeur peut être utilisé pour déplacer des charges dont le poids dépasse la capacité indiquée si le trajet est court.", False),
    Q("En cas de panne pendant une opération de levage, le conducteur doit sécuriser la zone avant d'intervenir.", True),
    Q("Le conducteur doit couper l'alimentation électrique ou le moteur avant toute opération de maintenance sur le gerbeur.", True),
    Q("Un gerbeur peut être conduit par un stagiaire non encore certifié, sous la seule surveillance orale d'un collègue.", False),
    Q("Le conducteur doit vérifier que le sol de l'entrepôt supporte la charge du gerbeur en fonctionnement.", True),
    Q("Il est permis de stocker des palettes en hauteur sans respecter la limite de charge du niveau du palettier.", False),
    Q("Le conducteur doit signaler tout croisement de piéton par un signal sonore si nécessaire.", True),
    Q("Un gerbeur peut circuler à pleine vitesse dans les allées étroites d'un entrepôt.", False),
    Q("Avant de charger ou décharger un véhicule, le conducteur doit vérifier que le véhicule est immobilisé.", True),
    Q("Le conducteur doit respecter la signalisation et le plan de circulation mis en place dans l'entrepôt.", True),
    Q("Un gerbeur en dysfonctionnement peut continuer d'être utilisé si le problème semble mineur.", False),
    Q("Le conducteur doit s'assurer que rien ni personne ne se trouve sous la charge levée.", True),
    Q("Il est interdit de laisser le gerbeur en fonctionnement sans surveillance avec une charge en hauteur.", True),
    Q("Le conducteur peut utiliser le gerbeur pour déplacer une charge en la faisant glisser au sol plutôt qu'en la levant.", False),
    Q("La vérification générale périodique du gerbeur doit être respectée selon la réglementation en vigueur.", True),
    Q("Le conducteur peut ignorer un balisage de sol temporaire s'il connaît bien l'entrepôt.", False),
    Q("Un gerbeur peut être utilisé pour dégerber des charges situées en hauteur sur un palettier instable.", False),
    Q("Le conducteur doit vérifier l'adéquation entre la charge à déplacer et la capacité du gerbeur avant toute opération.", True),
    Q("Il est permis de conduire le gerbeur en état de fatigue importante si le poste se termine bientôt.", False),
    Q("Le conducteur doit connaître l'emplacement des dispositifs d'arrêt d'urgence du gerbeur.", True),
    Q("Un gerbeur peut être utilisé en extérieur par temps de verglas sans adaptation particulière.", False),
    Q("Le conducteur doit rendre compte à son responsable de toute situation dangereuse rencontrée durant son poste.", True),
]

# ============================================================
# R489 - Chariots de manutention automoteurs à conducteur porté
# ============================================================
r489_cg = [
    Q("Le CACES R489 est valable 5 ans pour toutes les catégories.", True),
    Q("Le CACES R489 catégorie 1B dispense de la catégorie 1A.", True),
    Q("Le CACES R489 catégorie 2B dispense de la catégorie 2A.", True),
    Q("Un CACES d'une catégorie donne automatiquement le droit de conduire toutes les autres catégories de chariots.", False),
    Q("La conduite d'un chariot élévateur en entreprise nécessite une autorisation de conduite délivrée par l'employeur en plus du CACES.", True),
    Q("La catégorie 1A concerne les transpalettes à conducteur porté sans élévation du poste de conduite.", True),
    Q("La catégorie 1B concerne les gerbeurs à conducteur porté avec une hauteur de levée supérieure à 1,20 m.", True),
    Q("La catégorie 3 concerne les chariots élévateurs frontaux en porte-à-faux de capacité nominale supérieure à 6 tonnes.", False),
    Q("La catégorie 4 concerne les chariots élévateurs frontaux en porte-à-faux de capacité nominale supérieure à 6 tonnes.", True),
    Q("La catégorie 5 concerne les chariots élévateurs à mât rétractable.", True),
    Q("La catégorie 6 concerne les chariots à poste de conduite élévable, avec un plancher à plus de 1,20 m.", True),
    Q("La catégorie 7 concerne la conduite hors production de chariots de toutes catégories.", True),
    Q("En cas d'échec à une seule des deux épreuves, le candidat conserve le bénéfice de la partie réussie pendant 12 mois.", True),
    Q("La date d'obtention du CACES correspond à la date de réussite à la première des deux épreuves passées.", False),
    Q("Il faut réussir à la fois l'épreuve théorique et l'épreuve pratique pour obtenir le CACES R489.", True),
]

r489_techno = [
    Q("La stabilité d'un chariot élévateur en charge repose notamment sur le triangle de stabilité formé par les roues avant et le pivot de l'essieu arrière.", True),
    Q("Plus le mât est incliné vers l'avant en charge, plus le chariot est stable.", False),
    Q("Le centre de gravité de l'ensemble chariot-charge se déplace vers l'avant lorsque la charge est levée haut.", True),
    Q("Un chariot élévateur peut basculer latéralement dans un virage pris trop vite, même à vide.", True),
    Q("Le contrepoids à l'arrière du chariot sert à compenser le poids de la charge en porte-à-faux.", True),
    Q("La capacité de charge d'un chariot élévateur reste identique quelle que soit la hauteur de levée.", False),
    Q("Un chariot à mât rétractable permet de réduire l'encombrement en allée étroite par rapport à un chariot frontal classique.", True),
    Q("Un chariot tracteur industriel est conçu pour porter la charge sur un plateau fixe.", False),
    Q("Un chariot à plateau porteur porte la charge sur une plate-forme fixe, sans mât élévateur.", True),
    Q("Un chariot à poste de conduite élévable permet au cariste de circuler en hauteur avec son poste de conduite.", True),
    Q("Un transpalette (catégorie 1A) est équipé d'un mât élévateur de grande hauteur.", False),
    Q("Un gerbeur à conducteur porté (catégorie 1B) a une hauteur de levée supérieure à celle d'un transpalette catégorie 1A.", True),
    Q("Les pneumatiques d'un chariot élévateur influencent son adhérence et sa stabilité selon le type de sol.", True),
    Q("Un chariot élévateur en porte-à-faux repartit le poids de la charge sur l'essieu avant via le principe du contrepoids.", True),
    Q("La vitesse de translation d'un chariot n'a aucune influence sur son risque de renversement.", False),
    Q("Le dévers du sol augmente le risque de renversement latéral du chariot en charge.", True),
    Q("Un chariot élévateur peut se renverser vers l'avant en cas de freinage brutal avec une charge élevée.", True),
    Q("Les fourches d'un chariot élévateur doivent être adaptées à la largeur et au poids de la charge à manutentionner.", True),
    Q("Un limiteur de charge peut bloquer le levage en cas de dépassement de la capacité nominale du chariot.", True),
    Q("Le report de charge sur l'essieu arrière diminue lorsque le mât est incliné vers l'avant en charge.", True),
    Q("Les chariots à mât rétractable sont conçus pour circuler dans des allées plus étroites que les chariots frontaux classiques.", True),
    Q("Un chariot tracteur industriel (catégorie 2B) est destiné à porter la charge sur ses propres fourches.", False),
    Q("La hauteur du centre de gravité du chariot à vide n'a aucune influence sur sa stabilité.", False),
    Q("Un accessoire porté comme une pince ou une potence modifie le centre de gravité de l'ensemble et donc la stabilité du chariot.", True),
    Q("Le gonflage inégal des pneumatiques peut affecter la stabilité latérale du chariot.", True),
]

r489_tableau = [
    Q("La plaque de charge indique la capacité maximale du chariot en fonction de la hauteur de levée et du centre de gravité de la charge.", True),
    Q("Un accessoire porté peut réduire la capacité de charge effective du chariot par rapport à sa capacité nominale.", True),
    Q("Il est permis d'ignorer l'abaque de charge si le conducteur est expérimenté.", False),
    Q("La capacité nominale indiquée sur la plaque constructeur correspond généralement à une charge dont le centre de gravité est standard.", True),
    Q("Plus le centre de gravité de la charge est éloigné du mât, plus la capacité admissible réelle diminue.", True),
    Q("L'abaque de charges est propre à chaque modèle de chariot et à ses équipements.", True),
    Q("Une charge peut être manutentionnée sans consulter l'abaque si son poids semble inférieur à la capacité nominale affichée.", False),
    Q("La plaque de charge doit être remplacée ou complétée en cas de changement d'accessoire porté modifiant la capacité.", True),
    Q("En cas de doute sur la capacité réelle admissible pour une charge donnée, le conducteur doit consulter l'abaque avant de lever.", True),
    Q("Il est interdit d'utiliser un chariot dont la plaque de charge est absente ou illisible.", True),
]

r489_exploitation = [
    Q("Le port de la ceinture de sécurité est obligatoire lorsque le chariot en est équipé.", True),
    Q("Il est autorisé de soulever une personne sur les fourches sans plateforme homologuée.", False),
    Q("Le chariot doit circuler fourches basses, à environ 15 cm du sol, en dehors des opérations de manutention.", True),
    Q("Un chariot élévateur peut circuler à vitesse illimitée dans un entrepôt si l'allée est large.", False),
    Q("Le conducteur doit s'assurer de la stabilité de la charge avant tout déplacement.", True),
    Q("Il est possible de dépasser la capacité nominale du chariot pour une charge exceptionnelle et légère.", False),
    Q("En cas de croisement avec un piéton, le conducteur du chariot est prioritaire.", False),
    Q("Le klaxon doit être utilisé aux intersections et zones à visibilité réduite.", True),
    Q("Le chariot élévateur doit être stationné moteur coupé, frein de parking serré, fourches au sol, en fin de poste.", True),
    Q("Un chariot électrique en charge de batterie doit être surveillé en raison du risque de dégagement d'hydrogène.", True),
    Q("Le conducteur peut quitter son poste de conduite avec une charge en hauteur le temps de vérifier un document.", False),
    Q("La vitesse doit être adaptée à l'état du sol, à la charge transportée et à la visibilité.", True),
    Q("Le conducteur doit vérifier l'état des fourches et du mât avant la prise de poste.", True),
    Q("Il est permis de transporter une charge en la faisant dépasser largement le gabarit du chariot sans signalisation.", False),
    Q("Le conducteur doit adapter sa vitesse dans les zones de stockage à forte densité de piétons.", True),
    Q("Un chariot élévateur peut être utilisé pour pousser une palette au sol plutôt que de la soulever.", False),
    Q("Le conducteur doit s'assurer que l'allée de circulation est dégagée avant d'engager le chariot en marche arrière.", True),
    Q("Il est autorisé de gerber une charge sur un rack sans vérifier la capacité de charge du niveau.", False),
    Q("Le conducteur doit vérifier que le sol de l'entrepôt supporte le poids du chariot en charge.", True),
    Q("Un chariot peut circuler sur une rampe sans en connaître la pente maximale admissible.", False),
    Q("Le conducteur doit maintenir une distance de sécurité avec les autres chariots ou engins en mouvement.", True),
    Q("Il est possible de lever une charge tout en roulant à vitesse normale.", False),
    Q("La zone de dépose doit être dégagée de tout obstacle avant de poser la charge.", True),
    Q("Un chariot élévateur peut être conduit par un salarié non formé en cas d'urgence, sans certification.", False),
    Q("Le conducteur doit porter les équipements de protection individuelle adaptés à son poste.", True),
    Q("Il est interdit de manutentionner une charge instable ou mal palettisée.", True),
    Q("En cas de panne pendant une opération de levage, le conducteur doit sécuriser la zone avant d'intervenir.", True),
    Q("Le conducteur doit couper le contact avant toute intervention de maintenance sur le chariot.", True),
    Q("Un chariot élévateur peut être utilisé pour tracter un véhicule non prévu à cet effet, hors catégorie 2B.", False),
    Q("Le conducteur doit vérifier que le véhicule à charger ou décharger est immobilisé et calé avant l'opération.", True),
    Q("Il est permis d'ignorer la signalisation temporaire de chantier ou d'entrepôt si le trajet est habituel.", False),
    Q("Le conducteur doit s'assurer que rien ni personne ne se trouve sous une charge levée.", True),
    Q("Il est interdit de laisser un chariot en fonctionnement sans surveillance avec une charge en hauteur.", True),
    Q("Le conducteur peut utiliser un chariot pour déplacer une charge en la faisant glisser au sol plutôt qu'en la levant.", False),
    Q("La vérification générale périodique du chariot doit être respectée selon la réglementation en vigueur.", True),
    Q("Le conducteur peut ignorer un balisage de sol temporaire s'il connaît bien l'entrepôt.", False),
    Q("Le conducteur doit vérifier l'adéquation entre la charge à déplacer et la capacité du chariot avant toute opération.", True),
    Q("Il est permis de conduire un chariot élévateur en état de fatigue importante si le poste se termine bientôt.", False),
    Q("Le conducteur doit connaître l'emplacement des dispositifs d'arrêt d'urgence du chariot.", True),
    Q("Un chariot élévateur peut être utilisé en extérieur par temps de verglas sans adaptation particulière.", False),
    Q("Le conducteur doit rendre compte à son responsable de toute situation dangereuse rencontrée durant son poste.", True),
    Q("Le chargement d'un chariot tracteur (catégorie 2B) doit respecter la capacité de traction maximale autorisée.", True),
    Q("Un chariot à poste élevé (catégorie 6) doit être utilisé uniquement dans des allées prévues et sécurisées à cet effet.", True),
    Q("Le conducteur d'un chariot en conduite hors production (catégorie 7) doit respecter les mêmes règles de sécurité qu'en conduite normale.", True),
    Q("Il est permis d'empiler des charges au-delà de la hauteur maximale du palettier si l'espace le permet.", False),
    Q("Le conducteur doit signaler tout dysfonctionnement du chariot constaté en cours de poste.", True),
    Q("Un chariot élévateur peut être gare dans une zone de circulation sans frein de parking serré si la pente est faible.", False),
    Q("Le conducteur doit s'assurer de disposer d'une visibilité suffisante avant de circuler en marche arrière prolongée.", True),
    Q("Il est interdit de manutentionner une charge dont le poids ou le volume dépasse les capacités visuelles de contrôle du conducteur sans précaution supplémentaire.", True),
    Q("Le conducteur doit respecter le plan de circulation et la signalisation mis en place dans l'établissement.", True),
]

# ============================================================
# R482A - Engins de chantier
# ============================================================
r482_cg = [
    Q("Le CACES R482 est valable 10 ans quelle que soit la catégorie.", True),
    Q("La catégorie A du CACES R482 est réservée aux engins compacts d'une masse en service supérieure à 6 tonnes.", False),
    Q("La catégorie G permet la conduite hors production des engins des catégories A à F.", True),
    Q("La catégorie B1 concerne les engins d'extraction à déplacement séquentiel, comme les pelles hydrauliques de plus de 6 tonnes.", True),
    Q("La catégorie B2 concerne les engins de sondage/forage à déplacement séquentiel.", True),
    Q("La catégorie B3 concerne les engins rail-route à déplacement séquentiel.", True),
    Q("La catégorie C1 concerne les engins de chargement à déplacement alternatif, comme les chargeuses de plus de 6 tonnes.", True),
    Q("La catégorie D concerne les engins de compactage.", True),
    Q("La catégorie E concerne les engins de transport, comme les tombereaux.", True),
    Q("La catégorie F concerne les chariots de manutention tout-terrain.", True),
    Q("Un CACES R482 catégorie A donne automatiquement le droit de conduire tous les engins des autres catégories.", False),
    Q("La conduite d'un engin de chantier en entreprise nécessite une autorisation de conduite délivrée par l'employeur en plus du CACES.", True),
]

r482_techno = [
    Q("La stabilité d'un engin de chantier dépend de la nature du terrain, de sa pente et de la répartition de la charge.", True),
    Q("Une pelle hydraulique reste parfaitement stable quelle que soit l'inclinaison du terrain.", False),
    Q("Le godet chargé d'une chargeuse doit être maintenu bas pendant le déplacement pour améliorer la stabilité et la visibilité.", True),
    Q("Un bouteur peut travailler en toute sécurité en bordure de fouille sans précaution particulière.", False),
    Q("La pression au sol d'un engin sur chenilles est généralement inférieure à celle d'un engin sur pneus de masse équivalente.", True),
    Q("Le rayon de braquage d'un engin articulé est généralement plus court qu'un engin à châssis rigide de même gabarit.", True),
    Q("Les dispositifs de sécurité comme l'avertisseur de recul peuvent être désactivés si l'opérateur connaît bien le chantier.", False),
    Q("Une pelle hydraulique à déplacement séquentiel se déplace par appui sur ses vérins plutôt qu'en roulant en continu.", True),
    Q("Une niveleuse est conçue pour des opérations de nivellement fin du terrain.", True),
    Q("Un compacteur agit par la masse et/ou la vibration pour densifier un sol ou un enrobe.", True),
    Q("Un tombereau articulé est conçu pour le transport de matériaux sur des terrains accidentés.", True),
    Q("Un chariot de manutention tout-terrain peut être équipé d'un mât ou d'une flèche télescopique.", True),
    Q("La stabilité d'un engin sur chenilles est en général supérieure à celle d'un engin sur pneus sur terrain meuble.", True),
    Q("Le centre de gravité d'un engin de chantier se déplace en fonction de la position et du poids de son équipement de travail.", True),
    Q("Une chargeuse-pelleteuse peut travailler simultanément avec le godet avant et la pelle arrière sans perte de stabilité.", False),
    Q("Un engin équipé d'une flèche télescopique voit sa stabilité diminuer lorsque la flèche est déployée en hauteur et en portée maximale.", True),
    Q("Le contrepoids arrière d'un engin de chantier compense le porte-à-faux de l'équipement avant en charge.", True),
    Q("Une pelle hydraulique rail-route peut circuler à la fois sur route et sur rail selon sa configuration.", True),
    Q("Un engin de chantier peut se renverser latéralement dans une pente transversale trop importante par rapport à sa capacité.", True),
    Q("Les stabilisateurs d'un engin de sondage/forage doivent être correctement déployés avant le début des opérations.", True),
    Q("Une chargeuse à direction articulée modifie son centre de gravité pendant le virage.", True),
    Q("Le godet d'une chargeuse doit être positionne en position transport, basse et reculée, pendant les déplacements.", True),
    Q("Un tracteur agricole utilisé comme engin de chantier peut être équipé d'accessoires spécifiques modifiant sa stabilité.", True),
    Q("La vitesse de déplacement d'un engin n'a aucune influence sur son risque de renversement en virage.", False),
    Q("Un moto-basculeur transporte sa charge dans une benne généralement positionnée à l'avant du poste de conduite.", True),
    Q("Les dimensions et le type de pneumatiques d'un engin influencent son adhérence et sa stabilité selon le terrain.", True),
    Q("Un engin équipé d'une pince ou d'un accessoire de levage voit son centre de gravité modifié par rapport à sa configuration standard.", True),
    Q("Le blocage du différentiel peut être utile sur terrain glissant mais doit être désactivé pour les virages serrés.", True),
]

r482_exploitation = [
    Q("Avant la prise de poste, le conducteur doit effectuer une vérification visuelle et fonctionnelle de l'engin.", True),
    Q("Il est interdit de circuler avec une charge levée en hauteur sur un engin de chantier.", True),
    Q("Le conducteur peut quitter l'engin sans couper le moteur pour une courte absence.", False),
    Q("Sauter de l'engin plutôt que d'utiliser les moyens d'accès prévus est toléré en cas d'urgence.", False),
    Q("La présence de piétons dans la zone d'évolution de l'engin doit toujours être prise en compte et sécurisée.", True),
    Q("Une opération de levage avec un engin de chantier non équipé des dispositifs de sécurité appropries est interdite.", True),
    Q("Le conducteur peut réaliser une opération de levage de charge suspendue avec un godet standard sans accessoire adapte.", False),
    Q("Les distances de sécurité vis-à-vis des lignes électriques aériennes doivent être respectées lors des travaux en hauteur.", True),
    Q("Le conducteur d'engin de chantier n'a pas besoin de vérifier la présence de réseaux enterrés avant de creuser.", False),
    Q("En cas de conditions météo dégradées, l'activité peut nécessiter d'être arrêtée.", True),
    Q("L'engin doit être immobilisé en position stable avec les organes de travail poses au sol en fin de poste.", True),
    Q("Le conducteur doit vérifier l'adéquation entre la charge à déplacer ou lever et la capacité de l'engin avant toute opération.", True),
    Q("Il est permis d'utiliser un engin de chantier dont un dispositif de sécurité est hors service, en attendant la réparation.", False),
    Q("Le conducteur doit s'assurer que la zone de travail est balisée et sécurisée avant de démarrer les opérations.", True),
    Q("Un engin de chantier peut circuler à proximité d'une fouille sans vérifier la stabilité du bord de fouille.", False),
    Q("Le conducteur doit adapter sa vitesse aux conditions de circulation du chantier.", True),
    Q("Il est autorisé de transporter une personne sur le godet ou la lame d'un engin de chantier.", False),
    Q("Le conducteur doit s'assurer que rien ni personne ne se trouve dans la zone de manoeuvre de l'équipement de travail.", True),
    Q("Un engin de chantier peut être utilisé pour des opérations de levage de charges suspendues sans respecter les distances de sécurité applicables.", False),
    Q("Le conducteur doit vérifier que le sol supportera le poids de l'engin et de sa charge éventuelle.", True),
    Q("Il est permis d'ignorer le plan de circulation du chantier si le trajet est habituel.", False),
    Q("Le conducteur doit signaler tout dysfonctionnement constaté sur l'engin en cours d'utilisation.", True),
    Q("Un engin de chantier peut être conduit par un salarié non formé en cas d'absence du titulaire habituel.", False),
    Q("Le conducteur doit maintenir une distance de sécurité avec les autres engins en mouvement sur le chantier.", True),
    Q("Il est interdit de travailler avec un engin de chantier à proximité immédiate d'une tranchée non étayée sans précaution.", True),
    Q("Le conducteur peut lever une charge suspendue tout en déplaçant l'engin à vitesse normale.", False),
    Q("La zone de manoeuvre de l'engin doit être dégagée de tout obstacle avant le début des travaux.", True),
    Q("Un engin de chantier peut être gare en pente sans dispositif de calage ou de blocage particulier.", False),
    Q("Le conducteur doit porter les équipements de protection individuelle adaptés à son poste de travail.", True),
    Q("Il est interdit d'utiliser un engin de chantier dont les organes de sécurité sont défaillants.", True),
    Q("Le conducteur doit vérifier la stabilité du terrain avant d'implanter les stabilisateurs d'un engin de forage.", True),
    Q("Un engin de chantier peut circuler avec la benne ou le godet charge en position haute pour améliorer la visibilité.", False),
    Q("Le conducteur doit couper le moteur avant toute intervention de maintenance sur l'engin.", True),
    Q("Il est permis de faire fonctionner un engin de chantier dans un espace confiné sans ventilation adaptée si l'opération est courte.", False),
    Q("Le conducteur doit vérifier l'absence de personnes dans l'angle mort avant toute manoeuvre de recul.", True),
    Q("Un engin de chantier peut être utilisé pour pousser une charge que sa capacité ne permet pas de lever.", False),
    Q("Le conducteur doit respecter la signalisation temporaire mise en place sur le chantier.", True),
    Q("Il est interdit de quitter le poste de conduite avec l'équipement de travail en position haute.", True),
    Q("Le conducteur doit s'assurer de la stabilité d'un engin avant d'entamer une opération de levage.", True),
    Q("Un engin de chantier peut travailler à proximité d'un réseau électrique enterré sans consulter les plans de récolement.", False),
    Q("Le conducteur doit vérifier que l'accès au poste de conduite est dégagé et en bon état avant de monter dans l'engin.", True),
    Q("Il est permis de conduire un engin de chantier en état de fatigue importante si le poste se termine bientôt.", False),
    Q("Le conducteur doit connaître l'emplacement des dispositifs d'arrêt d'urgence de l'engin.", True),
    Q("Le conducteur doit rendre compte à son responsable de toute situation dangereuse rencontrée durant son poste.", True),
]

r482_circulation = [
    Q("Sur la voie publique, un engin de chantier doit respecter le Code de la route comme tout véhicule.", True),
    Q("La signalisation du chantier et le balisage de la zone de circulation des engins ne concernent que le conducteur de l'engin.", False),
    Q("Un engin de chantier peut être transporte sur porte-engins sans arrimage si le trajet est court.", False),
    Q("Le conducteur doit respecter les limitations de vitesse spécifiques au chantier, souvent inférieures à celles de la route.", True),
    Q("Un engin de chantier doit être équipé d'un éclairage et d'une signalisation conformes pour circuler de nuit ou par faible visibilité.", True),
    Q("Il est permis de croiser un autre engin dans une zone de circulation étroite sans ralentir.", False),
    Q("Le conducteur doit céder le passage aux engins prioritaires selon le plan de circulation du chantier.", True),
    Q("La circulation d'un engin de chantier sur une piste non stabilisée doit tenir compte du risque d'enlisement ou de glissement.", True),
    Q("Un engin de chantier peut franchir un passage à niveau ferroviaire sans précaution particulière.", False),
    Q("Le gabarit de l'engin doit être vérifié avant tout transport sur porte-engins ou circulation sous ouvrage.", True),
    Q("Le conducteur doit s'assurer de la visibilité et de la signalisation adéquate lors du chargement de l'engin sur un porte-engins.", True),
    Q("Un engin de chantier immobilisé sur une voie de circulation doit être signalé pour prévenir les autres usagers.", True),
]

r482_finposte = [
    Q("En fin de poste, le conducteur doit signaler toute anomalie constatée sur l'engin pendant son utilisation.", True),
    Q("Le conducteur peut laisser l'engin sur le chantier avec les clés sur le contact en fin de poste.", False),
    Q("En fin de poste, l'équipement de travail doit être pose au sol et le moteur coupé.", True),
    Q("Le carnet d'entretien ou de suivi de l'engin doit être renseigné en cas d'anomalie constatée en fin de poste.", True),
]

# ============================================================
# R486A - PEMP (nacelles)
# ============================================================
r486_cg = [
    Q("Le CACES R486 est valable 5 ans pour toutes les catégories (A, B, C).", True),
    Q("La catégorie C du CACES R486 concerne la conduite hors production des PEMP de catégorie A ou B.", True),
    Q("La catégorie A concerne les PEMP à élévation multidirectionnelle.", False),
    Q("Un salarié titulaire du CACES R486 catégorie B peut conduire sans autorisation de conduite de son employeur.", False),
    Q("La catégorie B concerne les PEMP à élévation multidirectionnelle.", True),
    Q("Le type 2, translation commandée depuis le châssis en position non basse, est exclu du champ d'application du CACES R486.", True),
    Q("Le type 1 correspond à une translation possible uniquement en position transport, position basse.", True),
    Q("Le type 3 correspond à une translation commandée depuis la plateforme en position haute.", True),
    Q("L'option chargement/déchargement sur porte-engins est incluse d'office dans le CACES catégorie C.", True),
    Q("Un CACES R486 catégorie A donne automatiquement le droit de conduire une PEMP de catégorie B.", False),
    Q("La conduite d'une PEMP en entreprise nécessite une autorisation de conduite délivrée par l'employeur en plus du CACES.", True),
    Q("En cas d'échec à une seule des deux épreuves, le candidat conserve le bénéfice de la partie réussie pendant 12 mois.", True),
    Q("Il faut réussir à la fois l'épreuve théorique et l'épreuve pratique pour obtenir le CACES R486.", True),
    Q("Le CACES R486 permet à lui seul la délivrance d'une AIPR.", False),
]

r486_techno = [
    Q("Une PEMP du groupe A à la projection verticale du centre de la plateforme toujours à l'intérieur des lignes de renversement.", True),
    Q("Une PEMP de type 3 permet une translation commandée depuis la plateforme en position haute.", True),
    Q("La stabilité d'une PEMP dépend notamment de la nature et de la pente du terrain d'implantation.", True),
    Q("Le vent n'a aucune influence sur la stabilité d'une PEMP en hauteur.", False),
    Q("Il est possible d'augmenter la charge admissible sur la plateforme en ajoutant des occupants supplémentaires sans limite.", False),
    Q("Les stabilisateurs doivent être correctement déployés et cales avant toute élévation, lorsque la PEMP en est équipée.", True),
    Q("Une PEMP du groupe B peut projeter le centre de la plateforme au-delà des lignes de renversement, contrairement au groupe A.", True),
    Q("Une PEMP à élévation verticale offre en général un déport horizontal de la plateforme plus limite qu'une PEMP à élévation multidirectionnelle.", True),
    Q("La hauteur de travail atteignable d'une PEMP diminue en général lorsque le déport horizontal augmente.", True),
    Q("Une PEMP sur porteur automoteur peut se déplacer en position haute uniquement si elle est de type 3.", True),
    Q("Une PEMP à ciseaux appartient généralement au groupe A, élévation verticale.", True),
    Q("Une PEMP à nacelle articulée ou télescopique appartient généralement au groupe B, élévation multidirectionnelle.", True),
    Q("Le calage des stabilisateurs sur un sol meuble doit se faire avec des platines de répartition adaptées.", True),
    Q("La charge admissible sur la plateforme diminue en général avec l'augmentation de la hauteur ou du déport.", True),
    Q("Une PEMP peut être utilisée sur un sol en dévers sans tenir compte des préconisations du constructeur sur la pente maximale admissible.", False),
    Q("Le report de charge sur les stabilisateurs d'une PEMP varie selon la position de la flèche ou du bras articulé.", True),
    Q("Une PEMP électrique est généralement privilégiée pour un usage en intérieur en raison de l'absence d'émissions polluantes.", True),
    Q("Un dispositif de limitation de dévers peut bloquer l'élévation si l'inclinaison du châssis dépasse la valeur admissible.", True),
    Q("La résistance du sol doit être compatible avec la charge ponctuelle exercée par les stabilisateurs ou les roues de la PEMP.", True),
    Q("Une PEMP de type 1 peut être déplacée en position haute avec la plateforme chargée.", False),
    Q("Le rayon d'action d'une PEMP à flèche télescopique est en général supérieur à celui d'une PEMP à ciseaux.", True),
    Q("Les organes de commande en plateforme doivent rester prioritaires par rapport à ceux situes au sol, sauf en cas de commande de secours.", True),
    Q("La vitesse du vent admissible en exploitation est indiquée par le constructeur et varie selon les modèles de PEMP.", True),
    Q("Un dispositif anti-écrasement doit protéger le conducteur en cas de contact du garde-corps avec un obstacle.", True),
    Q("Une PEMP peut être utilisée pour transporter du matériel en plus des personnes, dans la limite de la charge admissible indiquée par le constructeur.", True),
    Q("La stabilité d'une PEMP repose uniquement sur le poids du châssis, indépendamment de la position de la flèche.", False),
]

r486_exploitation = [
    Q("Le port du harnais avec longe attachée à un point d'ancrage dédié est obligatoire dans la nacelle, selon les préconisations du constructeur.", True),
    Q("Il est autorisé de sortir de la nacelle en hauteur pour accéder à une structure fixe sans dispositif de protection.", False),
    Q("Le conducteur doit vérifier l'absence d'obstacles aériens avant toute élévation.", True),
    Q("Une PEMP peut être utilisée pour élever une charge non arrimée sur la plateforme en plus des personnes.", False),
    Q("En cas de panne des commandes en hauteur, il existe une commande de secours au sol permettant de redescendre la plateforme.", True),
    Q("Le nombre de personnes dans la nacelle peut dépasser la limite indiquée par le constructeur si leur poids total reste faible.", False),
    Q("Le conducteur doit s'assurer que le sol supportera la charge de la PEMP et de ses stabilisateurs.", True),
    Q("Il est permis de déplacer la PEMP en position haute sans respecter les préconisations du constructeur sur le type de sol.", False),
    Q("Une distance de sécurité doit être respectée vis-à-vis des lignes électriques, variable selon la tension.", True),
    Q("Le conducteur peut utiliser la nacelle comme moyen de levage de matériaux avec un palan improvise.", False),
    Q("La zone d'évolution au sol de la PEMP doit être balisée pour protéger les tiers.", True),
    Q("En cas de vent fort dépassant les préconisations constructeur, l'utilisation de la PEMP doit être interrompue.", True),
    Q("Le conducteur doit connaître la procédure de secours en cas de blocage de la plateforme en hauteur.", True),
    Q("Avant toute utilisation, le conducteur doit vérifier l'état des commandes, des dispositifs de sécurité et de la structure de la PEMP.", True),
    Q("Il est interdit de se pencher au-dessus du garde-corps de la plateforme pendant l'élévation.", True),
    Q("Le conducteur peut modifier ou désactiver un dispositif de sécurité de la PEMP s'il gêne l'opération.", False),
    Q("Le conducteur doit s'assurer que la plateforme est en position basse avant de faire déplacer une PEMP de type 1.", True),
    Q("Une PEMP peut être utilisée en extérieur par temps orageux sans précaution particulière.", False),
    Q("Le conducteur doit vérifier l'adéquation entre le poids total, personnes et matériel, et la charge admissible avant l'élévation.", True),
    Q("Il est autorisé d'utiliser la plateforme comme moyen d'accès permanent à un poste de travail en hauteur, sans limite de durée.", False),
    Q("Le conducteur doit porter les équipements de protection individuelle adaptés selon l'analyse de risques.", True),
    Q("Une PEMP peut circuler à proximité d'une fouille ou d'un dénivelé sans vérifier la stabilité du terrain.", False),
    Q("Le conducteur doit s'assurer que les issues et zones d'évacuation restent dégagées lors du positionnement de la PEMP.", True),
    Q("Il est permis de transporter la PEMP en position haute d'un point à un autre du chantier si l'opérateur est expérimenté, pour un type 1.", False),
    Q("Le conducteur doit maintenir une distance de sécurité avec les autres engins et installations du site.", True),
    Q("Une PEMP peut être utilisée pour soulever une charge suspendue au moyen d'un crochet fixé sur le garde-corps.", False),
    Q("Le conducteur doit vérifier que le sol reste stable pendant toute la durée de l'opération, notamment en cas de pluie.", True),
    Q("Il est interdit de quitter la plateforme en hauteur sans autorisation et sans dispositif de protection adapte.", True),
    Q("Le conducteur doit s'assurer de la présence et du bon fonctionnement du dispositif de commande de secours au sol avant élévation.", True),
    Q("Une PEMP peut être utilisée pour des travaux à proximité de lignes électriques sans respecter les distances minimales réglementaires.", False),
    Q("Le conducteur doit signaler tout dysfonctionnement constaté sur la PEMP en cours d'utilisation.", True),
    Q("Il est permis de conduire une PEMP en état de fatigue importante si le poste se termine bientôt.", False),
    Q("Le conducteur doit connaître l'emplacement des dispositifs d'arrêt d'urgence de la PEMP.", True),
    Q("Une PEMP peut être stabilisée sur des cales de fortune non prévues par le constructeur si nécessaire.", False),
    Q("Le conducteur doit s'assurer que la zone de travail au sol est signalée pour empêcher l'accès aux tiers pendant l'utilisation de la PEMP.", True),
    Q("Il est interdit d'utiliser une PEMP dont un dispositif de sécurité est hors service, en attendant réparation.", True),
    Q("Le conducteur doit s'assurer que le poids maximal autorisé par plateforme comprend le poids des personnes et du matériel embarqué.", True),
    Q("Une PEMP de catégorie C peut être utilisée pour transporter du matériel sur porte-engins sans respecter les consignes d'arrimage.", False),
    Q("Le conducteur doit vérifier la présence de la notice d'instructions et du carnet de maintenance de la PEMP avant utilisation.", True),
    Q("Il est permis d'utiliser la plateforme pour élever une échelle ou un moyen d'accès supplémentaire pour atteindre une hauteur non prévue.", False),
    Q("Le conducteur doit adapter la vitesse de translation de la PEMP aux conditions du terrain et à la présence de tiers.", True),
    Q("Une PEMP peut être utilisée à proximité d'une zone de circulation de véhicules sans balisage particulier.", False),
    Q("Le conducteur doit s'assurer que les commandes au sol restent accessibles en cas d'urgence.", True),
    Q("Il est interdit de surcharger la plateforme au-delà de la charge maximale indiquée par le constructeur, même temporairement.", True),
    Q("Le conducteur doit vérifier que le dispositif anti-écrasement de la plateforme fonctionne correctement avant utilisation.", True),
    Q("Une PEMP peut être garée en fin de poste avec la plateforme en position haute pour gagner du temps le lendemain.", False),
    Q("Le conducteur doit rendre compte à son responsable de toute situation dangereuse rencontrée durant son poste.", True),
    Q("Il est permis d'utiliser une PEMP pour des opérations de levage de charges non liées à un poste de travail en hauteur.", False),
    Q("Le conducteur doit vérifier que l'accès à la plateforme est en bon état avant de monter.", True),
    Q("Une PEMP peut être utilisée sans respecter le plan de prévention établi avec l'entreprise utilisatrice du site.", False),
    Q("Le conducteur doit s'assurer que la plateforme est correctement fermée avant toute élévation.", True),
    Q("Il est interdit de fumer ou d'utiliser une flamme nue à bord de la plateforme lors de travaux à proximité de matières inflammables.", True),
    Q("Le conducteur doit vérifier que le terrain d'implantation ne comporte pas de cavité ou de zone récemment remblayée avant de positionner la PEMP.", True),
    Q("Le conducteur doit respecter les consignes spécifiques du site lors de l'utilisation de la PEMP.", True),
]

r486_entretien = [
    Q("Une vérification générale périodique est requise pour les PEMP, comme pour les autres équipements de travail concernes.", True),
    Q("Le conducteur n'a pas à signaler un dysfonctionnement mineur constaté en fin de poste s'il n'empêche pas le fonctionnement.", False),
    Q("Le carnet de maintenance de la PEMP doit être tenu à jour et disponible sur site.", True),
    Q("Il est permis d'utiliser une PEMP dont la vérification générale périodique est expirée si l'utilisation reste occasionnelle.", False),
    Q("Le conducteur doit vérifier le niveau des fluides selon la fréquence indiquée par le constructeur.", True),
    Q("En fin de poste, la PEMP doit être stationnée en position de repos, plateforme basse, et mise hors tension selon les préconisations constructeur.", True),
]

# ============================================================
# Assemble
# ============================================================
def build_ref(code, libelle, thèmes):
    out = {"code": code, "libelle": libelle, "seuil_reussite_global_pct": 70, "seuil_reussite_par_theme": "moyenne", "themes": []}
    for theme_code, theme_libelle, barème, qlist in thèmes:
        questions = []
        for i, q in enumerate(qlist, start=1):
            qid = f"{code}-{theme_code.upper()[:4]}-{i:02d}"
            questions.append({"id": qid, "enonce": q["enonce"], "reponse": q["reponse"]})
        out["themes"].append({
            "code": theme_code,
            "libelle": theme_libelle,
            "bareme_officiel_sur_100": barème,
            "questions": questions
        })
    return out

data = {
    "version": "2.0",
    "date_generation": "2026-08-04",
    "note": "Banque générée automatiquement par Claude à partir des référentiels CNAMTS/INRS (R485, R489, R482A, R486A) présents dans le dossier ressources. Format vrai/faux, 100 questions par référentiel répartie par thème selon les barèmes officiels. A FAIRE VALIDER par un formateur CACES avant toute mise en production.",
    "referentiels": [
        build_ref("R485", "Gerbeurs à conducteur accompagnant", [
            ("connaissances_generales", "Connaissances générales", 15, r485_cg),
            ("technologie_stabilite", "Technologie et stabilité des gerbeurs", 25, r485_techno),
            ("tableau_charges", "Tableau / abaque de charges", 10, r485_tableau),
            ("exploitation", "Exploitation des gerbeurs", 50, r485_exploitation),
        ]),
        build_ref("R489", "Chariots de manutention automoteurs à conducteur porté", [
            ("connaissances_generales", "Connaissances générales", 15, r489_cg),
            ("technologie_stabilite", "Technologie et stabilité des chariots", 25, r489_techno),
            ("tableau_charges", "Tableau / abaque de charges", 10, r489_tableau),
            ("exploitation", "Exploitation des chariots", 50, r489_exploitation),
        ]),
        build_ref("R482A", "Engins de chantier", [
            ("connaissances_generales", "Connaissances générales", 12, r482_cg),
            ("technologie_stabilite", "Technologie et stabilité des engins de chantier", 28, r482_techno),
            ("exploitation", "Exploitation des engins de chantier", 44, r482_exploitation),
            ("circulation", "Circulation des engins de chantier", 12, r482_circulation),
            ("fin_poste_maintenance", "Fin de poste et maintenance", 4, r482_finposte),
        ]),
        build_ref("R486A", "Plates-formes elevatrices mobiles de personnel (PEMP)", [
            ("connaissances_generales", "Connaissances générales", 14, r486_cg),
            ("technologie_stabilite", "Technologie et stabilité des PEMP", 26, r486_techno),
            ("exploitation", "Exploitation des PEMP", 54, r486_exploitation),
            ("entretien", "Entretien", 6, r486_entretien),
        ]),
    ]
}

with open("questions_qcm.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

total = 0
for ref in data["referentiels"]:
    n = sum(len(t["questions"]) for t in ref["themes"])
    total += n
    print(ref["code"], n)
print("TOTAL", total)
